# Generated by Django 4.2 on 2023-05-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0002_alter_account_email_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='forget_password_token',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='forget_password_token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
