# Generated by Django 4.2 on 2023-05-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0004_customer_account_forget_password_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
