# Generated by Django 4.2 on 2023-05-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0005_previouspassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
